(function() {var implementors = {};
implementors["libc"] = [];implementors["syntex_syntax"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='syntex_syntax/codemap/struct.BytePos.html' title='syntex_syntax::codemap::BytePos'>BytePos</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='syntex_syntax/codemap/struct.CharPos.html' title='syntex_syntax::codemap::CharPos'>CharPos</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a> for <a class='struct' href='syntex_syntax/parse/parser/struct.Restrictions.html' title='syntex_syntax::parse::parser::Restrictions'>Restrictions</a>",];implementors["cheddar"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='syntex_syntax/parse/parser/struct.Restrictions.html' title='syntex_syntax::parse::parser::Restrictions'>Restrictions</a>&gt; for <a class='struct' href='syntex_syntax/parse/parser/struct.Restrictions.html' title='syntex_syntax::parse::parser::Restrictions'>Restrictions</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='syntex_syntax/codemap/struct.BytePos.html' title='syntex_syntax::codemap::BytePos'>BytePos</a>&gt; for <a class='struct' href='syntex_syntax/codemap/struct.BytePos.html' title='syntex_syntax::codemap::BytePos'>BytePos</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/ops/trait.Sub.html' title='core::ops::Sub'>Sub</a>&lt;<a class='struct' href='syntex_syntax/codemap/struct.CharPos.html' title='syntex_syntax::codemap::CharPos'>CharPos</a>&gt; for <a class='struct' href='syntex_syntax/codemap/struct.CharPos.html' title='syntex_syntax::codemap::CharPos'>CharPos</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
